# Netlify configuration for Portfolio Website

[build]
  # Build command (not needed for static site, but good to have)
  command = "npm run build"
  # Directory to publish (current directory since it's a static site)
  publish = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect rules for SPA-like behavior
[[redirects]]
  # Handle client-side routing for projects.html
  from = "/projects"
  to = "/projects.html"
  status = 200

[[redirects]]
  # Handle privacy policy
  from = "/privacy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  # Handle terms of service
  from = "/terms"
  to = "/terms-of-service.html"
  status = 200

[[redirects]]
  # Handle cookie policy
  from = "/cookies"
  to = "/cookie-policy.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    # Don't cache HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    # Cache JavaScript files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    # Cache CSS files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    # Cache images for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these will be set in Netlify dashboard)
# SUPABASE_URL and SUPABASE_ANON_KEY should be configured in Netlify UI

# Form handling (if you want to use Netlify Forms as backup)
# Uncomment if you want Netlify to handle contact forms as well
# [[plugins]]
#   package = "@netlify/plugin-forms"

# Performance optimizations
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true